demo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=100 )
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class myuploadfile(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
    f_name = models.CharField(max_length=255)
    myfiles = models.FileField(upload_to='')

    def __str__(self):
        return self.f_name

class MyModel(models.Model):
    upload = models.FileField(upload_to='')
# def getdata(instance, filename):
#     return instance.user.id
# a=getdata()
# print(a)

templates/dangki.html
<!--{% load static %}-->
<!--<!doctype html>-->
<!--<html lang="en">-->
<!--  <head>-->
<!--  	<title>Sign Up </title>-->
<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->

<!--	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">-->

<!--	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">-->

<!--	<link rel="stylesheet" href="{% static 'asset2/css/style.css' %}">-->

<!--	</head>-->
<!--	<body class="img" style="background-image: url(https://gvn360.com/wp-content/uploads/2020/05/04_gettyimages-474389277_resized-2.jpg);">-->
<!--	<section class="ftco-section">-->
<!--		<div class="container">-->
<!--			<div class="row justify-content-center">-->
<!--				<div class="col-md-6 text-center mb-5">-->
<!--					<h2 class="heading-section">Đăng kí </h2>-->
<!--				</div>-->
<!--			</div>-->
<!--			<div class="row justify-content-center">-->
<!--				<div class="col-md-7 col-lg-5">-->
<!--					<div class="login-wrap">-->

<!--						<form action="" method="post" class="signup-form">-->
<!--							{% if messages %}-->

<!--                        {% for message in messages %}-->
<!--                        <div class="alert alert-info">-->
<!--                            {{ message }}-->
<!--                        </div>-->
<!--                        {% endfor %}-->

<!--                    {% endif %}-->
<!--							{% csrf_token %}-->
<!--		      		<div class="form-group mb-3">-->
<!--		      			<label class="label" for="name">Tên người dùng</label>-->
<!--		      			<input type="text" class="form-control" placeholder="John Doe" autocomplete="off" name="username">-->
<!--		      			<span class="icon fa fa-user-o"></span>-->
<!--		      		</div>-->
<!--		      		<div class="form-group mb-3">-->
<!--		      			<label class="label" for="email">Email </label>-->
<!--		      			<input type="text" class="form-control" placeholder="johndoe@gmail.com"  name="email">-->
<!--		      			<span class="icon fa fa-paper-plane-o"></span>-->
<!--		      		</div>-->
<!--	            <div class="form-group mb-3">-->
<!--	            	<label class="label" for="password">Mật khẩu</label>-->
<!--	              <input id="password" type="password" class="form-control" placeholder="Password" name="password">-->
<!--	              <span class="icon fa fa-lock"></span>-->
<!--	            </div>-->
<!--	            <div class="form-group">-->
<!--	            	<button type="submit" class="form-control btn btn-primary submit px-3">Đăng kí</button>-->
<!--	            </div>-->
<!--	          </form>-->
<!--	          <p>Bạn đã có tài khoản? <a href="{% url 'login_attempt'%}">Đăng nhập</a></p>-->
<!--	        </div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</section>-->

<!--	<script src="{% static 'asset2/js/jquery.min.js' %}"></script>-->
<!--  <script src="{% static 'asset2/js/popper.js' %}"></script>-->
<!--  <script src="{% static 'asset2/js/bootstrap.min.js' %}"></script>-->
<!--  <script src="{% static 'asset2/js/main.js' %}"></script>-->

<!--	</body>-->
<!--</html>-->
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- register24:03-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css ' %}">
    <!--[if lt IE 9]>
		<script src="assets/js/html5shiv.min.js"></script>
		<script src="assets/js/respond.min.js"></script>
	<![endif]-->
</head>

<body>
    <div class="main-wrapper  account-wrapper">
        <div class="account-page">
            <div class="account-center">
                <div class="account-box">
                    <form action="" class="form-signin" method="post">
						{% csrf_token %}
						<div class="account-logo">
                            <a href="index-2.html"><img src="{% static 'assets/img/logo-dark.png' %}" alt=""></a>
                        </div>
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" name="username">
                        </div>
                        <div class="form-group">
                            <label>Email Address</label>
                            <input type="email" class="form-control" name="email">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name="password">
                        </div>

                        <div class="form-group text-center">
                            <button class="btn btn-primary account-btn" type="submit">Signup</button>
                        </div>
                        <div class="text-center login-link">
                            Already have an account? <a href="login.html">Login</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/app.js ' %}"></script>
</body>


<!-- register24:03-->
</html>

templates/error.html
    {% block content %}


    <div class="global-container">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">Error</h3>

            <a href="/" class="btn btn-success">Back</a>
            
            </div>
        </div>
    </div>
    </div>
    

    {% endblock %}

templates/forgot-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- forgot-password24:03-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css ' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css ' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css ' %}">
    <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js ' %}"></script>
		<script src="{% static 'assets/js/respond.min.js ' %}"></script>
	<![endif]-->
</head>

<body>

    <div class="main-wrapper account-wrapper">
        <div class="account-page">
			<div class="account-center">
                <div class="account-box">
                    <form class="form-signin" method="post">
                         {% csrf_token %}
						<div class="account-logo">
                            <a href="index-2.html"><img src="assets/img/logo-dark.png" alt=""></a>
                        </div>
                        <div class="form-group">
                            <label>Enter Your Email</label>
                            {{form.as_p}}
                        </div>
                        <div class="form-group text-center">
                            <button class="btn btn-primary account-btn" type="submit">Reset Password</button>
                        </div>
                        <div class="text-center register-link">
                            <a href="login.html">Back to Login</a>
                        </div>
                    </form>
                </div>
			</div>
        </div>
    </div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/app.js ' %}"></script>
</body>


<!-- forgot-password24:03-->
</html>

templates/home.html
{% extends './index.html' %}
    {% block content %}
        <div class="content">
                        {% if messages %}

                        {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
        </div>
    {% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- index22:59-->
<head>
    <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <div class="header">
			<div class="header-left">
				<a href="{% url 'home' %}" class="logo">
					<img src="{% static 'assets/img/logo.png' %}" width="35" height="35" alt=""> </i> <span><h4>Thể tích phổi</h4></span>
				</a>
			</div>

            <a id="mobile_btn" class="mobile_btn float-left" href="#sidebar"><i class="fa fa-bars"></i></a>
            <ul class="nav user-menu float-right">
                <li class="nav-item dropdown d-none d-sm-block">
                    <div class="dropdown-menu notifications">
                        <div class="topnav-dropdown-header">
                            <span>Notifications</span>
                        </div>
                        <div class="drop-scroll">
                            <ul class="notification-list">
                                <li class="notification-message">
                                    <a href="activities.html">
                                        <div class="media">
											<span class="avatar">
												<img alt="John Doe" src="{% static 'assets/img/user.jpg' %}" class="img-fluid">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">John Doe</span> added new task <span class="noti-title">Patient appointment booking</span></p>
												<p class="noti-time"><span class="notification-time">4 mins ago</span></p>
											</div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="topnav-dropdown-footer">
                            <a href="activities.html">View all Notifications</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown d-none d-sm-block">

                </li>
                <li class="nav-item dropdown has-arrow pl-3">
                    <a href="#" class="dropdown-toggle nav-link user-link" data-toggle="dropdown">
                        <span class="user-img">
							<img class="rounded-circle" src="{% static 'assets/img/user.jpg' %}" width="24" alt="Admin">
							<span class="status online"></span>
						</span>
						<span>{{request.user}}</span>
                    </a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="{% url 'password_change' %}">Thay đổi mật khẩu</a>
						<a class="dropdown-item" href="{% url 'dangxuat' %}">Đăng xuất</a>
					</div>
                </li>
            </ul>
        </div>
        <div class="sidebar" id="sidebar">
            <div class="sidebar-inner slimscroll">
                <div id="sidebar-menu" class="sidebar-menu">
                    <ul>
                       <li class="menu-title">Chính</li>
						<li>

                            <a href=""><i class="fa fa-upload" aria-hidden="true"></i> <span>Quản lý file</span></a>
                        </li>
                        <li>
							<a href=""><i class="fa fa-list" aria-hidden="true"></i> <span>Thống kê lần sử dụng </span> </a>

						</li>

                        <li>
                            <a href=""><i class="fa fa-cog"></i> <span>Thiết lập</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="page-wrapper">
            <div class="content">
                {% block content %}

                {% endblock %}
            </div>
            <div class="notification-box">
                <div class="msg-sidebar notifications msg-noti">
                    <div class="topnav-dropdown-header">
                        <span>Messages</span>
                    </div>
                    </div>
                    <div class="topnav-dropdown-footer">
                        <a href=" ">See all messages</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar-overlay" data-reff=""></div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'assets/js/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/js/chart.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>

</body>


<!-- index22:59-->
</html>

templates/myfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'upload' %}" method="POST" enctype="multipart/form-data">
<!--        <input type="text" name="filename"  placeholder="enter your file name" >-->
<!--        <input type="file" multiple name="uploadfiles" >-->
        <input type="text" name="filename"  placeholder="enter your file name" >
        <input type="text" id="directories" name="" hidden/>
        <input type="file" id="file_input" name="uploadfiles" webkitdirectory directory/>


        {% csrf_token %}
        <button type="submit" >File Upload</button>
    </form>

    {% for d in nd.myuploadfile_set.all %}

   <p> {{d.f_name}} ---- <a href="{{d.myfiles.url}}" download=""><img width="50" src="{{d.myfiles.url}}"></p></a>

    {% endfor %}

</body>
<script>
 files = document.querySelector("#file_input").files;
 document.querySelector("#file_input").addEventListener("change", function() {
    files = document.querySelector("#file_input").files;
    var directories = {}
    for (var file of files) {
      file.webkitRelativePath
      directories[file.name] = file.webkitRelativePath
    }
    directories = JSON.stringify(directories);
    document.querySelector("#directories").value = directories
 });
</script>
</html>

templates/password_change.html
{% extends 'index.html' %}

{% block title %} Change Password {% endblock %}

{% block content %}
<h1>Change Password</h1>

<p>
    Use the form below to change your Password
</p>

<p>Please use the following form to login: </p>

<form method="post">
    {{form.as_p}}
    <p><input type="submit" value="Change"></p>
    {% csrf_token %}
</form>
{% endblock %}

templates/password_change_done.html
{% extends 'index.html' %}

{% block title %} Password Changed {% endblock %}

{% block content %}
<p>Bạn đã đổi mật khẩu thành công</p>
<a href="{% url 'home' %} ">Trang chủ</a>
{% endblock %}

templates/password_reset_complete.html
{% extends 'index.html' %}

{% block title %}Password reseted {% endblock %} 

{% block content %}

<h1> Password set</h1>

<p>


Mật khẩu của bạn đã được thiết lập
</p>

<p>

</p>
<p> Bạn có thể <a href="{% url 'login_attempt' %}">Đăng nhập</a></p>
{% endblock %}

templates/password_reset_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- index22:59-->
<head>
    <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
</head>


{% block content %}


<h1> Reset your password</h1>
{% if validlink %} 
<p>
    Please enter your new password twice :
</p>
<form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <p><input type="submit" value='Change my password' ></p>
</form>
{% else %}
<p>
    The password reset link was invaild possibly because it has already been used.
    Please request a new password
    {% endif %}
</p>
{% endblock %}

    <div class="sidebar-overlay" data-reff=""></div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'assets/js/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/js/chart.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>

</body>


<!-- index22:59-->
</html>

templates/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- index22:59-->
<head>
    <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
</head>



{% block content %} 
<h1>Thiết lập lại mật khẩu</h1>
<p>Chúng tôi đã gửi cho bạn hướng dẫn qua email để cài đặt mật khẩu của bạn </p>
<p>Nếu bạn không nhận được email, hãy đảm bảo rằng bạn đã nhập địa chỉ email của mình</p>
<a href="https://mail.google.com/mail/u/">Truy cập Email của bạn</a>
{% endblock %}
    <div class="sidebar-overlay" data-reff=""></div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'assets/js/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/js/chart.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>

</body>


<!-- index22:59-->
</html>

templates/password_reset_email.html
Someone asked for Passowrd Reset for Email {{ email }}
<h1>Follow the link :</h1>
{{ protocol }}://{{domain}}{% url 'password_reset_confirm' uidb64=uid token=token %}
Your username, in case you have forgotten: {{user.get_username}}

templates/password_reset_form.html
<!--{% extends './index.html' %}-->
<!--    {% block content %}-->

<!--<body>-->

<!--                    <h1>{% block title %} Thay đổi mật khẩu bằng Email {% endblock %}</h1>-->

<!--                    <p>-->
<!--                    Nhập email của bạn:-->
<!--                    </p>-->

<!--                    <form method="post">-->
<!--                    {{form.as_p}}-->
<!--                    <p><input type="submit" value="Gửi Email" ></p>-->
<!--                    {% csrf_token %}-->

<!--                    </form>-->

<!--    {% endblock %}-->

{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- forgot-password24:03-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css ' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css ' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css ' %}">
    <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js ' %}"></script>
		<script src="{% static 'assets/js/respond.min.js ' %}"></script>
	<![endif]-->
</head>

<body>
    <div class="main-wrapper account-wrapper">
        <div class="account-page">
			<div class="account-center">
                <div class="account-box">
                    <form class="form-signin" action="#">
						<div class="account-logo">
                            <a href="index-2.html"><img src="assets/img/logo-dark.png" alt=""></a>
                        </div>
                        <div class="form-group">
                            <label>Enter Your Email</label>
                            <input type="text" class="form-control" autofocus>
                        </div>
                        <div class="form-group text-center">
                            <button class="btn btn-primary account-btn" type="submit">Reset Password</button>
                        </div>
                        <div class="text-center register-link">
                            <a href="login.html">Back to Login</a>
                        </div>
                    </form>
                </div>
			</div>
        </div>
    </div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/app.js ' %}"></script>
</body>


<!-- forgot-password24:03-->
</html>

templates/token_send.html
    {% block content %}


    
    <div class="global-container">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">Chúng tôi đã gửi một email tới bạn.Vui lòng xác thực </h3>
            <div class="card-text text-center">
                Vui lòng kiểm tra email
            </div>
        </div>
    </div>
    </div>


    {% endblock %}